### ISSUE TITLE
Trouble installing on Mac OSX 11.6 (Big Sur)

### ISSUE THREAD

**Issue by knobelsp** [nasa/MINX#2]
Hi,
I'm having trouble installing on a Mac running OSX 11.6 (Big Sur). The specific message I get is:

"MINX4.app can't be opened because Apple cannot check it for malicious software
This software needs to be updated. Contact the developer for more information."

Any suggestions?
Thanks

**Comment by sval-dev** [comment]
The MINX app has not been notarized for newer OS X versions. 
See Apple's ["how to open a mac app from an unidentified developer"](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac) to open the app.

You may also be interested in the information on the issue over at Apple's ["Safely open apps on your Mac article"](https://support.apple.com/en-us/HT202491).

We do plan to release an updated version of MINX to support Big Sur, but currently IDL (which MINX is built on), only supports up to OS X 10.15 Catalina according to their [platform support table](https://www.l3harrisgeospatial.com/docs/platformsupporttable.html).

**Comment by knobelsp** [comment]
However, I still can't get this to work after opening with the procedure for unidentified developers. I receive this message after selecting 'run':

Can’t make file "Macintosh HD:private:var:folders:0z:5rj667gd5n1cd8zvltq6yz540000gp:T:AppTranslocation:F36E232B-960E-45D6-869C-5BB5163A161C:dUtils_applescripts.scpt" into type file. (-1700)

FWIW, this is a NASA/EUSO laptop, but I do have administrative privileges. 

Thanks

**Comment by sval-dev** [comment]
Hi Kirk,

Glad to hear MINX opened now but sorry to hear you're still having trouble!

That error looks like app translocation in action. 

Where on the filesystem are you running MINX from? 
Have you drag moved it someplace like your Desktop or the Applications folder?

Please try moving the contents of the MINX distribution some place other than the distributed/mounted disk image (dmg) and try again.

I have heard that the actual applescript file, even when it runs might be throwing errors under Big Sur in some cases.
The workaround in that case is manually running the minx.sav file with the bundled IDL virtual machine.

From a terminal in the distribution directory (i.e. that directory that contains MINX.app, minx.sav, the idl87 folder:
`./idl87/bin/idl -vm minx.sav`

As I mentioned, we are planning a new MINX release that copes with some of these issues, but until the underlying IDL platform officially supports the new OSes I'm afraid we may not be able to get full support without workarounds.

P.S. Hope you're doing well since our ACEPOL collaboration!

**Comment by knobelsp** [comment]
Hi Sebastian,

Sorry for the delay in my response. Ultimately I was never able to get MINX working, even if I moved the file to be launched to other locations. I am running Big Sur. My ulterior motive here was to understand how people have been visualizing and working with multi-angle data, since we want to build that capability into SeaDAS (https://seadas.gsfc.nasa.gov/) in preparation for PACE. So I don't immediately have files to process and can wait until your team makes updates. I don't think plume height identification would be something we want to do with SeaDAS, but it would be nice to have some way to identify the proper altitude for the multi view angle 'aggregation' to cloud top. We're planning determining cloud top height other ways too, but parallax is a first order tool that I'd like to have.

In any case, thanks, and nice to be in touch again!
Kirk






Kirk D. Knobelspiesse (he/him/his)

NASA Goddard Space Flight Center, Ocean Ecology Laboratory

https://science.gsfc.nasa.gov/sed/bio/kirk.d.knobelspiesse
https://pace.gsfc.nasa.gov

________________________________
From: Sebastian Val ***@***.***>
Sent: Tuesday, September 28, 2021 2:44 PM
To: nasa/MINX ***@***.***>
Cc: Kirk K. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [nasa/MINX] Trouble installing on Mac OSX 11.6 (Big Sur) (#2)


Hi Kirk,

Glad to hear MINX opened now but sorry to hear you're still having trouble!

That error looks like app translocation in action.

Where on the filesystem are you running MINX from?
Have you drag moved it someplace like your Desktop or the Applications folder?

Please try moving the contents of the MINX distribution some place other than the distributed/mounted disk image (dmg) and try again.

I have heard that the actual applescript file, even when it runs might be throwing errors under Big Sur in some cases.
The workaround in that case is manually running the minx.sav file with the bundled IDL virtual machine.

From a terminal in the distribution directory (i.e. that directory that contains MINX.app, minx.sav, the idl87 folder:
./idl87/bin/idl -vm minx.sav

As I mentioned, we are planning a new MINX release that copes with some of these issues, but until the underlying IDL platform officially supports the new OSes I'm afraid we may not be able to get full support without workarounds.

P.S. Hope you're doing well since our ACEPOL collaboration!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnasa%2FMINX%2Fissues%2F2%23issuecomment-929527284&data=04%7C01%7Ckirk.d.knobelspiesse%40nasa.gov%7C04776ddf2bd2482ae76d08d982b00846%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637684514839251228%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6NkLXLBh6S9OmyprQ7BwdWMPMyJmTBI8iWGBvHHRG94%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.%20com%2Fnotifications%2Funsubscribe-auth%2FAMYX2BCRLP43ZK3EE7LGV7DUEIEIVANCNFSM5E4LRSPA&data=04%7C01%7Ckirk.knobelspiesse%40nasa.gov%7C95b5ee2545884261377308d982b00018%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637684514697491777%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NPjfroP%2F4Q5aG4UkKPhxoC0b6W65BtrEoDumrviGfjE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckirk.d.knobelspiesse%40nasa.gov%7C04776ddf2bd2482ae76d08d982b00846%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637684514839261193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iFI%2FhzaPP4CFxxPeMvku%2B1y9k7d%2BS1LlD4gTI32Phno%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckirk.d.knobelspiesse%40nasa.gov%7C04776ddf2bd2482ae76d08d982b00846%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637684514839271140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cSvh1Thw3d5jJZuG%2BQ9JygG8tddvc%2FKDARWe27oyTn8%3D&reserved=0>.
